### ISSUE TITLE
Attempt to Cancel or Save an Item Edit produces error (and crashes out)

### ISSUE THREAD

**Issue by ka6sox** [ka6sox/hidb#7]
![image](https://user-images.githubusercontent.com/509613/202691219-0c714d18-c100-425e-ac75-447efe066ecb.png)

**Comment by ka6sox** [comment]
it crashed the 1st time and the 2nd...but after that it seems to be working? don't understand this.

**Comment by dburr** [comment]
This should be fixed in 56fb7404f19f7ec8f1f7f94a4a852e067b7046f4
